CABINET_OPTIONS = {
    "Vice President": {
        "Name": "Kamala Harris",
        "Profile Picture": "https://example.com/kamala_harris.jpg",
        "Skill": "Leadership and Justice Advocacy",
        "Personality": "Confident, resilient, and pragmatic",
        "Expertise": "Law enforcement, civil rights, and public policy",
        "Backstory": "A former prosecutor and Senator from California, Kamala Harris is the first female Vice President of the United States, representing a trailblazing achievement in American politics.",
        "Motivations": "To advance equity, civil rights, and economic justice for all Americans.",
    },
    "Secretary of State": {
        "Name": "Marco Rubio",
        "Profile Picture": "https://example.com/marco_rubio.jpg",
        "Skill": "Foreign Policy Advocacy",
        "Personality": "Charismatic, strategic, and outspoken",
        "Expertise": "International relations and Latin American affairs",
        "Backstory": "A Senator from Florida with Cuban heritage, Rubio has long championed strong U.S. foreign policy and a robust approach to global leadership.",
        "Motivations": "To promote American values abroad and strengthen national security through diplomacy.",
    },
    "Secretary of the Treasury": {
        "Name": "Janet Yellen",
        "Profile Picture": "https://example.com/janet_yellen.jpg",
        "Skill": "Economic Strategy",
        "Personality": "Analytical, deliberate, and data-driven",
        "Expertise": "Macroeconomics, monetary policy, and public finance",
        "Backstory": "A former Federal Reserve Chair, Janet Yellen is the first woman to serve as Treasury Secretary, renowned for her economic expertise and measured approach.",
        "Motivations": "To stabilize the economy and ensure sustainable growth with equitable wealth distribution.",
    },
    "Secretary of Defense": {
        "Name": "Pete Hegseth",
        "Profile Picture": "https://example.com/pete_hegseth.jpg",
        "Skill": "Military Strategy and Media Influence",
        "Personality": "Outspoken, patriotic, and results-oriented",
        "Expertise": "Veterans' affairs and military readiness",
        "Backstory": "A Fox News contributor and Army National Guard veteran, Hegseth brings a media-savvy approach to defense policy.",
        "Motivations": "To strengthen military capabilities and uphold American dominance on the global stage.",
    },
    "Attorney General": {
        "Name": "Matt Gaetz",
        "Profile Picture": "assets/cabinet_members/matt_gaetz.jpg",
        "Skill": "Legal Policy and Public Advocacy",
        "Personality": "Controversial, combative, and polarizing",
        "Expertise": "Conservative legal reform and government oversight",
        "Backstory": "A Congressman from Florida known for his staunch defense of conservative values and fierce criticism of political opponents.",
        "Motivations": "To protect conservative ideals and uphold constitutional freedoms.",
    },
    "Secretary of the Interior": {
        "Name": "Doug Burgum",
        "Profile Picture": "https://example.com/doug_burgum.jpg",
        "Skill": "Rural Development and Conservation",
        "Personality": "Innovative, entrepreneurial, and practical",
        "Expertise": "Energy policy and public land management",
        "Backstory": "A tech entrepreneur and North Dakota Governor, Burgum emphasizes innovation in energy and rural economic growth.",
        "Motivations": "To balance economic development with environmental stewardship.",
    },
    "Secretary of Agriculture": {
        "Name": "Tom Vilsack",
        "Profile Picture": "https://example.com/tom_vilsack.jpg",
        "Skill": "Agricultural Policy and Rural Development",
        "Personality": "Pragmatic, experienced, and collaborative",
        "Expertise": "Farm policy and rural economic growth",
        "Backstory": "A former Iowa Governor and longstanding Secretary of Agriculture, Vilsack has deep expertise in supporting American farmers.",
        "Motivations": "To sustain American agriculture and protect rural communities.",
    },
    "Secretary of Commerce": {
        "Name": "Gina Raimondo",
        "Profile Picture": "https://example.com/gina_raimondo.jpg",
        "Skill": "Economic Innovation",
        "Personality": "Ambitious, analytical, and forward-thinking",
        "Expertise": "Business development and economic policy",
        "Backstory": "A former Governor of Rhode Island, Raimondo has championed economic innovation and infrastructure development.",
        "Motivations": "To modernize the economy and support American businesses on the global stage.",
    },
    "Secretary of Labor": {
        "Name": "Marty Walsh",
        "Profile Picture": "https://example.com/marty_walsh.jpg",
        "Skill": "Labor Advocacy",
        "Personality": "Pragmatic, empathetic, and action-oriented",
        "Expertise": "Union leadership and workforce development",
        "Backstory": "A former Mayor of Boston and union leader, Walsh has worked to improve workers' rights and job opportunities.",
        "Motivations": "To promote fair labor practices and strengthen workers' protections.",
    },
    "Secretary of Health and Human Services": {
        "Name": "Robert F. Kennedy Jr.",
        "Profile Picture": "https://example.com/rfk_jr.jpg",
        "Skill": "Public Health Advocacy",
        "Personality": "Outspoken, controversial, and passionate",
        "Expertise": "Environmental health and vaccine safety",
        "Backstory": "A Kennedy family member and environmental activist, RFK Jr. is known for his unconventional views on health policies.",
        "Motivations": "To challenge conventional health narratives and advocate for transparency.",
    },
    "Secretary of Housing and Urban Development": {
        "Name": "Marcia Fudge",
        "Profile Picture": "https://example.com/marcia_fudge.jpg",
        "Skill": "Urban Development and Housing Advocacy",
        "Personality": "Tenacious, empathetic, and community-focused",
        "Expertise": "Affordable housing and urban policy",
        "Backstory": "A former Congresswoman from Ohio, Fudge has championed fair housing and community revitalization.",
        "Motivations": "To address housing inequality and improve urban living standards.",
    },
    "Secretary of Transportation": {
        "Name": "Pete Buttigieg",
        "Profile Picture": "https://example.com/pete_buttigieg.jpg",
        "Skill": "Infrastructure and Urban Policy",
        "Personality": "Measured, innovative, and articulate",
        "Expertise": "Infrastructure modernization and smart cities",
        "Backstory": "A former Mayor of South Bend and 2020 presidential candidate, Buttigieg is focused on rebuilding America’s infrastructure.",
        "Motivations": "To modernize transportation systems and support economic mobility.",
    },
    "Secretary of Energy": {
        "Name": "Chris Wright",
        "Profile Picture": "https://example.com/chris_wright.jpg",
        "Skill": "Energy Innovation and Policy",
        "Personality": "Visionary, innovative, and pragmatic",
        "Expertise": "Renewable energy and fossil fuel integration",
        "Backstory": "Chris Wright is a tech entrepreneur and CEO of Liberty Energy, focused on optimizing energy production with sustainability.",
        "Motivations": "To balance energy independence with environmental responsibility.",
    },
    "Secretary of Education": {
        "Name": "Miguel Cardona",
        "Profile Picture": "https://example.com/miguel_cardona.jpg",
        "Skill": "Educational Equity and Policy",
        "Personality": "Empathetic, innovative, and community-focused",
        "Expertise": "K-12 education reform and higher education access",
        "Backstory": "A former teacher and Connecticut Commissioner of Education, Cardona has championed equity in education for underserved communities.",
        "Motivations": "To close the achievement gap and modernize the American education system.",
    },
    "Secretary of Veterans Affairs": {
        "Name": "Doug Collins",
        "Profile Picture": "https://example.com/doug_collins.jpg",
        "Skill": "Veteran Advocacy and Policy",
        "Personality": "Pragmatic, dedicated, and patriotic",
        "Expertise": "Veteran services and military benefits",
        "Backstory": "A former Congressman and military chaplain, Doug Collins has worked to improve resources for veterans and their families.",
        "Motivations": "To honor the service of veterans and ensure they receive the care they deserve.",
    },
    "Secretary of Homeland Security": {
        "Name": "Kristi Noem",
        "Profile Picture": "https://example.com/kristi_noem.jpg",
        "Skill": "Homeland Security and Border Policy",
        "Personality": "Resilient, strategic, and outspoken",
        "Expertise": "Border security and emergency management",
        "Backstory": "The Governor of South Dakota, Noem is known for her firm stance on national security and limited government intervention.",
        "Motivations": "To strengthen border defenses and ensure national resilience against threats.",
    },
    "White House Chief of Staff": {
        "Name": "Susie Wiles",
        "Profile Picture": "https://example.com/susie_wiles.jpg",
        "Skill": "Political Strategy and Leadership",
        "Personality": "Pragmatic, charismatic, and results-driven",
        "Expertise": "Campaign management and executive coordination",
        "Backstory": "A seasoned political strategist, Wiles has been instrumental in organizing successful campaigns for high-profile politicians.",
        "Motivations": "To streamline the administration's agenda and build a cohesive leadership team.",
    },
    "EPA Administrator": {
        "Name": "Lee Zeldin",
        "Profile Picture": "https://example.com/lee_zeldin.jpg",
        "Skill": "Environmental Policy Advocacy",
        "Personality": "Determined, pragmatic, and forward-thinking",
        "Expertise": "Clean energy and environmental sustainability",
        "Backstory": "A former Congressman from New York, Zeldin has balanced economic and environmental priorities in his policy work.",
        "Motivations": "To protect the environment while ensuring economic growth.",
    },
    "OMB Director": {
        "Name": "Shalanda Young",
        "Profile Picture": "https://example.com/shalanda_young.jpg",
        "Skill": "Budget Management and Policy",
        "Personality": "Detail-oriented, analytical, and collaborative",
        "Expertise": "Federal budget and public policy",
        "Backstory": "Shalanda Young has served in key budgetary roles in Congress, earning bipartisan respect for her expertise.",
        "Motivations": "To ensure fiscal responsibility while advancing national priorities.",
    },
    "U.S. Trade Representative": {
        "Name": "Katherine Tai",
        "Profile Picture": "https://example.com/katherine_tai.jpg",
        "Skill": "Trade Negotiation and Policy",
        "Personality": "Strategic, diplomatic, and detail-focused",
        "Expertise": "International trade and economic agreements",
        "Backstory": "The first Asian-American U.S. Trade Representative, Tai is known for her expertise in complex trade negotiations.",
        "Motivations": "To secure equitable trade deals that benefit American workers and industries.",
    },
    "U.N. Ambassador": {
        "Name": "Elise Stefanik",
        "Profile Picture": "https://example.com/elise_stefanik.jpg",
        "Skill": "International Relations and Advocacy",
        "Personality": "Articulate, strategic, and ambitious",
        "Expertise": "Foreign policy and global diplomacy",
        "Backstory": "A Congresswoman from New York, Stefanik has been a rising star in international policy discussions.",
        "Motivations": "To strengthen America’s voice on the global stage and advocate for democratic values.",
    },
    "Council of Economic Advisers Chairman": {
        "Name": "Cecilia Rouse",
        "Profile Picture": "https://example.com/cecilia_rouse.jpg",
        "Skill": "Economic Research and Policy",
        "Personality": "Analytical, collaborative, and pragmatic",
        "Expertise": "Labor economics and public policy",
        "Backstory": "The first African-American woman to chair the Council of Economic Advisers, Rouse brings deep expertise in economic research.",
        "Motivations": "To develop data-driven policies that promote sustainable economic growth.",
    },
    "Small Business Administrator": {
        "Name": "Isabella Casillas Guzman",
        "Profile Picture": "https://example.com/isabella_guzman.jpg",
        "Skill": "Small Business Advocacy",
        "Personality": "Empathetic, resourceful, and practical",
        "Expertise": "Entrepreneurship and small business development",
        "Backstory": "The head of the U.S. Small Business Administration, Guzman has focused on empowering small businesses to thrive.",
        "Motivations": "To support small businesses as the backbone of the American economy.",
    },
    "U.S. Immigration and Customs Enforcement Director": {
        "Name": "Tom Homan",
        "Profile Picture": "https://example.com/tom_homan.jpg",
        "Skill": "Immigration Enforcement and Policy",
        "Personality": "Determined, strategic, and authoritative",
        "Expertise": "Border security and immigration law",
        "Backstory": "A former ICE director, Homan has championed stricter immigration controls and enforcement policies.",
        "Motivations": "To protect national borders and ensure lawful immigration processes.",
    },
    "National Security Advisor": {
        "Name": "Michael Waltz",
        "Profile Picture": "https://example.com/michael_waltz.jpg",
        "Skill": "National Defense and Policy",
        "Personality": "Disciplined, strategic, and action-oriented",
        "Expertise": "Military strategy and counterterrorism",
        "Backstory": "A Congressman and Green Beret, Waltz has extensive experience in defense and foreign policy.",
        "Motivations": "To secure the nation from threats and advance strategic military goals.",
    },
    "White House Counsel": {
        "Name": "William McGinley",
        "Profile Picture": "https://example.com/william_mcginley.jpg",
        "Skill": "Legal Counsel and Policy",
        "Personality": "Analytical, pragmatic, and meticulous",
        "Expertise": "Constitutional law and executive policy",
        "Backstory": "An experienced White House lawyer, McGinley has worked on numerous legal and policy issues for past administrations.",
        "Motivations": "To ensure legal integrity in executive decision-making.",
    },
    "Solicitor General": {
        "Name": "Dean John Sauer",
        "Profile Picture": "https://example.com/dean_john_sauer.jpg",
        "Skill": "Supreme Court Advocacy",
        "Personality": "Strategic, detail-oriented, and persuasive",
        "Expertise": "Appellate law and constitutional advocacy",
        "Backstory": "An experienced litigator, Sauer has argued complex cases before the Supreme Court.",
        "Motivations": "To advocate for the administration’s legal positions with precision.",
    },
    "CIA Director": {
        "Name": "John Ratcliffe",
        "Profile Picture": "https://example.com/john_ratcliffe.jpg",
        "Skill": "Intelligence and National Security",
        "Personality": "Resilient, analytical, and decisive",
        "Expertise": "Intelligence analysis and counterespionage",
        "Backstory": "A former DNI, Ratcliffe has a history of strong positions on intelligence and national security.",
        "Motivations": "To safeguard American interests through robust intelligence operations.",
    },
    "Director of National Intelligence": {
        "Name": "Tulsi Gabbard",
        "Profile Picture": "https://example.com/tulsi_gabbard.jpg",
        "Skill": "National Intelligence Policy",
        "Personality": "Independent, pragmatic, and principled",
        "Expertise": "Defense and intelligence policy",
        "Backstory": "A former Congresswoman and Army officer, Gabbard brings a unique perspective to national intelligence.",
        "Motivations": "To balance national security with constitutional liberties.",
    },
    "U.S. Ambassador to Israel": {
        "Name": "Mike Huckabee",
        "Profile Picture": "https://example.com/mike_huckabee.jpg",
        "Skill": "Diplomacy and Advocacy",
        "Personality": "Charismatic, religious, and outspoken",
        "Expertise": "Middle Eastern policy and U.S.-Israel relations",
        "Backstory": "A former Governor and staunch supporter of Israel, Huckabee has been an advocate for U.S.-Israel partnerships.",
        "Motivations": "To strengthen ties with Israel and promote peace in the region.",
    },
    "Department of Government Efficiency": {
        "Name": "Elon Musk",
        "Profile Picture": "https://example.com/elon_musk.jpg",
        "Skill": "Innovation and Disruption",
        "Personality": "Visionary, ambitious, and eccentric",
        "Expertise": "Technology and organizational efficiency",
        "Backstory": "The founder of Tesla and SpaceX, Musk is known for his revolutionary ideas in business and technology.",
        "Motivations": "To bring efficiency and innovation to government systems.",
    },
    "White House Press Secretary": {
        "Name": "Karoline Leavitt",
        "Profile Picture": "https://example.com/karoline_leavitt.jpg",
        "Skill": "Media Relations and Communication",
        "Personality": "Articulate, confident, and assertive",
        "Expertise": "Political communication and media strategy",
        "Backstory": "A rising star in conservative media, Leavitt has served as a communications advisor for high-profile politicians.",
        "Motivations": "To convey the administration’s message effectively and counter misinformation.",
    },
}

